### ISSUE TITLE
Couldn't match files for checkpoint

### ISSUE THREAD

**Issue by kinfeparty** [neuroailab/VIE#10]
Hi, Now I can train the model sucessfully and thanks for your great work. Now I met a small question.  I want to train the model in another dataset. I copy the code and rename the filename such as VIE-master2. And I want to load the original model .
Maybe some code needed to be modified,  the terminal shows **Couldn't match files for checkpoint ** in the VIE-master with the ckpt I need to load.   I change the cache_dir to VIE-master2 in run_training.sh.But why the code read the VIE-mater filefolder. And I didn't find any parameter of VIE-master.
Can you help me solve this little question?

**Comment by chengxuz** [comment]
can you describe your situation more? Through running `run_training.sh`, are you trying to train first the IR and then the LA model? And you want to start from a pretrained model on a different dataset (I assume this pretrained model is also trained with `run_training.sh`)?

If that's true, I believe you need to modify some codes in the setting script: https://github.com/neuroailab/VIE/blob/master/tf_model/saved_settings/vd_3dresnet_fx.py#L6.
You should look at how the loading is configured for the LA training (https://github.com/neuroailab/VIE/blob/master/tf_model/saved_settings/vd_3dresnet_fx.py#L24) and then do similar things in the IR function.

Hope this helps.

**Comment by kinfeparty** [comment]
Sorry for the misunderstanding! Because I want to train a new model on another dataset, so I rename the original filefolder's name VIE-master to VIE-master2. I want to reload the IR model. Which means I want to start from a pretrained model on the same dataset. The only difference is the filefolder's name.       the terminal shows ** Couldn't match files for checkpoint in the VIE-master/video_pub_cache/models/vd_unsup_fx/dyn_clstr/vd_3dresnet_IR/model.ckpt-15000**      But this checkpoint is in the VIE-master2 filefolder. I have already rename the the cache_dir to VIE-master2 in run_training.sh.   Beacause the log error is  refurbishd so I can‘t show the image. Am I describe clear enough?

**Comment by chengxuz** [comment]
I don't understand why this is happening, if you modify the cache_dir value at https://github.com/neuroailab/VIE/blob/master/tf_model/run_training.sh#L4, you should have set the save directory to VIE-master2, instead of VIE-master. I would look at the value of cache_dir at this position: https://github.com/neuroailab/VIE/blob/master/tf_model/train_vie.py#L309 and this position: https://github.com/neuroailab/VIE/blob/master/tf_model/framework.py#L130. They should both be under the VIE-master2, if they are not, something must be wrong.

**Comment by kinfeparty** [comment]
ok,I will have a try.
