### ISSUE TITLE
experiment settings

### ISSUE THREAD

**Issue by YuanLiuuuuuu** [neuroailab/VIE#12]
can't tell all these setting functions in vd_single_frame_fx.py corresponding to which experiment in your paper. If I want to train a VIE-Single, which setting should I choose?

**Comment by chengxuz** [comment]
To train VIE-Single, you need to modify the https://github.com/neuroailab/VIE/blob/master/tf_model/run_training.sh. The IR_setting there should be this one: https://github.com/neuroailab/VIE/blob/master/tf_model/saved_settings/vd_single_frame_fx.py#L27, the main_setting should be https://github.com/neuroailab/VIE/blob/master/tf_model/saved_settings/vd_single_frame_fx.py#L82.

Sorry I should have this written somewhere in the README, will to do that if I have time recently.

**Comment by YuanLiuuuuuu** [comment]
What dose "a4" mean in load_from_slowfast_a4_IR? Could you please give some interpretations about the function name in these setting function?

**Comment by chengxuz** [comment]
`a4` means that the fast stream in the SlowFast network is a variant of the original slowfast model. The recommended fast stream has 32 frame samples from 64 consecutive frames, which is very computation expensive. So I decreseased the number of frames to 16, which corresponds to `alpha=4`, in the terms of the SlowFast paper (the original `alpha` is 8). Sorry I should have added more explanations into the README or scripts.

**Comment by seuyou** [comment]
> `a4` means that the fast stream in the SlowFast network is a variant of the original slowfast model. The recommended fast stream has 32 frame samples from 64 consecutive frames, which is very computation expensive. So I decreseased the number of frames to 16, which corresponds to `alpha=4`, in the terms of the SlowFast paper (the original `alpha` is 8). Sorry I should have added more explanations into the README or scripts.

**Comment by YuanLiuuuuuu** [comment]
Thank you for your answer.
