### ISSUE TITLE
Bugs in training slow fast model

### ISSUE THREAD

**Issue by YuanLiuuuuuu** [neuroailab/VIE#14]
https://github.com/neuroailab/VIE/blob/9c0ad08487dccbe5d2cd1826dd4a6ca452c3d667/tf_model/model/instance_model.py#L177
You should pass train to training explicitly, eg. training=train, or just like your current code, it will raise exception.

**Comment by chengxuz** [comment]
you are right, `slowfast_single_pooling` is added later after I have finished the model training, so I did not notice this problem, sorry for the inconvenience. I have already fixed this in my latest commit.
