### ISSUE TITLE
Speed of training slowfast model

### ISSUE THREAD

**Issue by YuanLiuuuuuu** [neuroailab/VIE#15]
Hi, now I am training the slowfast model, and I will have to spend about 370ms per step with batch size  64 and I am training on 4 Nvidia V100 cards. Is this speed normal and any suggestions to accelerate the training process?

Thank you

**Comment by chengxuz** [comment]
Yeah, this speed looks reasonable to me. I don't have very good suggestions about accelerating, you can use change image resolutions to 112, it will make the training faster, but the model will also perform worse. I have not tried advanced acceleration settings like using float16.
