### ISSUE TITLE
Restoring params

### ISSUE THREAD

**Issue by YuanLiuuuuuu** [neuroailab/VIE#18]
Hi, when you trained resnet3d model, you first pretrained it with IR loss, and after 50, 000 steps you trained it with LA loss. I want to ask whether you load the labels from IR to initialize the clustered_labels in training LA?

**Comment by chengxuz** [comment]
The clustered_labels for LA will be computed at beginning, I do not load it from anywhere. Even if you are loading from a pretrained LA model, this variable will be recomputed at the beginning, that's how the program is written. See the first_flag in this sentence: https://github.com/neuroailab/VIE/blob/master/tf_model/train_vie.py#L567.
