### ISSUE TITLE
Training batch size

### ISSUE THREAD

**Issue by kinfeparty** [neuroailab/VIE#20]
Hello! I have a question on the training batch size.
I train the 3dresnet18 and I print the tensor shape.

The output tensor shape is (64,256,2,7,7) and(160,256,2,7,7)
What's the meaning of batch size 160? I didn't find this parameter.

**Comment by chengxuz** [comment]
Can I ask which tensors you are printing out?

**Comment by kinfeparty** [comment]
> Can I ask which tensors you are printing out?

The tensor in res3 block .

The output is  
(64,256,2,7,7) 
(64,256,2,7,7) 
(160,256,2,7,7)
(160,256,2,7,7)

just like this.   And I want to know the parameters 160 .

**Comment by chengxuz** [comment]
I have printed all tensors in function `_building_block_v2` and find that none of them have 160 as first dimension size. Can I ask whether you have modified the codes yourself? Can you show me how you printed the tensors to let me know what tensor is in this shape?

**Comment by kinfeparty** [comment]
> I have printed all tensors in function `_building_block_v2` and find that none of them have 160 as first dimension size. Can I ask whether you have modified the codes yourself? Can you show me how you printed the tensors to let me know what tensor is in this shape?

eh, I didn't modify the code. I add the print() in this position.

  if projection_shortcut is not None:
    shortcut = projection_shortcut(inputs)

  inputs = conv3d_fixed_padding(
      inputs=inputs, filters=filters, kernel_size=3, 
      time_kernel_size=3, strides=strides,
      data_format=data_format, time_stride=strides)

  inputs = batch_norm(inputs, training, data_format)
  inputs = tf.nn.relu(inputs)
  inputs = conv3d_fixed_padding(
      inputs=inputs, filters=filters, kernel_size=3, 
      time_kernel_size=3, strides=1,
      data_format=data_format)

 # print(inputs.shape)#

  

  return inputs + shortcut




The result is just like

(64, 128, 4, 14, 14)                                                                   
(64, 256, 2, 7, 7)                                                                                   
(64, 256, 2, 7, 7)                                                                                   
(64, 512, 1, 4, 4)                                                                                   
(64, 512, 1, 4, 4)                                                                                   
(160, 64, 8, 28, 28)                                                                                 
(160, 64, 8, 28, 28)                                                                                 
(160, 128, 4, 14, 14) .

**Comment by chengxuz** [comment]
Ah, I see, the tensors with 160 in the first dimension are for validation runs, where the batch size is 16 and there are multiple clips sampled from one video, making the first dimension 160. During training, the batch size is 64.

**Comment by kinfeparty** [comment]
I got it!
