### ISSUE TITLE
How to train the model with multi_gpu

### ISSUE THREAD

**Issue by kinfeparty** [neuroailab/VIE#21]
Hello,I want to train the model with multi_gpu,  I change the code in run_training.sh"gpu=0" to "gpu=0,1"

the code in train_vie.py got an error.
assert len(nn_clusterings) == multi_gpu.
because len(nn_clusterings) is 1 but mulit_gpu is 2.

Is there anyother code I need to change?

**Comment by chengxuz** [comment]
Did you use tfutils to run the script?

**Comment by kinfeparty** [comment]
I tried.It requires mongodb,which is hard to install on the server(because I am not administrator).So I thought if you can give me any suggestion.

**Comment by chengxuz** [comment]
You can start a mongodb on your local computer and then do a port forwarding from your computer to the server to make the mongodb visible by the process. If you are not familiar with this process, just search for "mongodb port forwarding".

**Comment by kinfeparty** [comment]
Thanks for your answering! I will have a try.

**Comment by kinfeparty** [comment]
> You can start a mongodb on your local computer and then do a port forwarding from your computer to the server to make the mongodb visible by the process. If you are not familiar with this process, just search for "mongodb port forwarding".

Finally I can use tfutils train the model,but I found the it can't read the original model which didn't trained by the tfutils. Is there any parameter I need to change for loading the original model?

**Comment by chengxuz** [comment]
You can add a new key `from_ckpt` to the `load_params` at line 343 of `train_vie.py`, the value of this new key should be the path to your checkpoint.
