### ISSUE TITLE
Downloading kinetics dataset

### ISSUE THREAD

**Issue by kinfeparty** [neuroailab/VIE#4]
Hello, I try to use  download_videos.py download the dataset.The code run but the videos aren't in the folder.
![2020-08-24 14-14-48屏幕截图](https://user-images.githubusercontent.com/35788879/91009963-31f38a00-e614-11ea-96d6-d3c60fb9f3fc.png)
Is there anything wrong in the code?

**Comment by chengxuz** [comment]
The code will download the videos to `vd_dwnld`. Can you check whether there are avi files there?

**Comment by kinfeparty** [comment]
![2020-08-25 12-13-09屏幕截图](https://user-images.githubusercontent.com/35788879/91122227-5dd24680-e6cc-11ea-9148-adbc818d8996.png)
The vd_dwnld filefolder is empty,only the label filefolder. If the video download unsucessfully will the Progress bar move?

**Comment by chengxuz** [comment]
yes, even for unsuccessful downloads, the progress bar will still move. I think there are some videos downloaded, you can wait to see if the size of vd_dwnld changes at all.

**Comment by kinfeparty** [comment]
Ok, I think my terminal need a VPN for downloading the video.

**Comment by wzx95789** [comment]
> Ok, I think my terminal need a VPN for downloading the video.

Hello, i come across some problems about downloading the video, could you teach me how you successfully download the video? My email is Wzx95789@163.com.

**Comment by kinfeparty** [comment]
> > Ok, I think my terminal need a VPN for downloading the video.
> 
> Hello, i come across some problems about downloading the video, could you teach me how you successfully download the video? My email is [Wzx95789@163.com](mailto:Wzx95789@163.com).

The dataset is too big,So I just download a little.  You need to download to download the video with VPN. Because the code runs in terminal, You also need to download proxychains. Please see the tutorial in the website.
