### ISSUE TITLE
can't start training

### ISSUE THREAD

**Issue by kinfeparty** [neuroailab/VIE#5]
Hello, I try to train the network. My tensorflow version is 1.13.2. I follow your tutorial and run **sh run_training.sh**.
![2020-08-24 17-38-56屏幕截图](https://user-images.githubusercontent.com/35788879/91028922-b5bb6f80-e630-11ea-8f00-74303c8094d9.png)

I found that the IR_setting don't work fine.The mission has no computation(great57) for hours and doesn't show errors.

I found that the code in framework.py   **line 185 :train_res = self.sess.run(self.train_targets)** don't work and return no response. 

Can you help me solve the bug? I'm not quite familiar with tensorflow.@chengxuz

**Comment by chengxuz** [comment]
Can you provide me more information? For example, can you check whether the data loading is successful?

**Comment by kinfeparty** [comment]
> Can you provide me more information? For example, can you check whether the data loading is successful?

Sorry! I found that the datafolder is wrong.

**Comment by kinfeparty** [comment]
Hello,It's me again. Finally I can start training on my own dataset.
But when the progress reach 75%.  An error occurs.
![2020-08-31 17-18-33屏幕截图](https://user-images.githubusercontent.com/35788879/91704308-06d9df00-ebae-11ea-8657-1fd757421e74.png)

It seems a question of batch_size. I found that the test_batch_size is 32 in vd_slow_fx.py. I didn't modify the val code.  Even if I change the batch_size to 3.
![2020-08-31 23-46-56屏幕截图](https://user-images.githubusercontent.com/35788879/91739302-50ddb780-ebe4-11ea-87e4-a8977efdfd77.png)
Is there anything wrong?

**Comment by chengxuz** [comment]
Hi, this is because the size of the validation videos you have is different from mine, you should recompute that number and correspondingly modify it (look at https://github.com/neuroailab/VIE/blob/master/tf_model/train_vie.py#L65)

**Comment by kinfeparty** [comment]
I got it.

**Comment by wzx95789** [comment]
> I got it.

Hello, thank you for your help. when i start training, i found there are no model.ckpt-50000 file. Can you tell me where to get it ?Thanks.

**Comment by kinfeparty** [comment]
> > I got it.
> 
> Hello, thank you for your help. when i start training, i found there are no model.ckpt-50000 file. Can you tell me where to get it ?Thanks.

You need to train the IR-model first.

**Comment by wzx95789** [comment]
> > Can you provide me more information? For example, can you check whether the data loading is successful?
> 
> Sorry! I found that the datafolder is wrong.

thanks for your help. when i train an IR model, the image loading has something wrong, have you ever met the same problem?
<img width="642" alt="微信图片_20200917133218" src="https://user-images.githubusercontent.com/70683510/93426820-4fec9b80-f8ef-11ea-9121-4e5ec8408546.png">
