### ISSUE TITLE
The number of item in the file can not match the number in the code--download_videos.py

### ISSUE THREAD

**Issue by Kaye-here** [neuroailab/VIE#6]
Hi Chengxu,thank you very much for your open source and paper,that's very helpful .
But I encounter somes questions about the code in download_videos.py.
There are just five items in the file named train.csv : label,youtube_id,time_start,time_end,split.
However,the code named download_vedios.py needs the sixth items of the file .
look at the code 
` 'id': line_split[1], 
  'sta': int(float(line_split[2])),
  'end': int(float(line_split[3])),
  'train': line_split[4], 
  'flag': int(line_split[5]), 
  'indx': curr_indx}`
So,what's the function of the flag?Is there has some error in the code or I've made some mistakes about the code.
Look forward to your reply

**Comment by chengxuz** [comment]
Hi Kaye,

In my downloaded csv file, each file has 6 items: label,youtube_id,time_start,time_end,split,is_cc.

Can you verify that you have donwloaded the csv files for kinetics-400?

**Comment by Kaye-here** [comment]
Hello, I downloaded kinetics400.tar.gz in this website:[https://deepmind.com/research/open-source/kinetics](url). 
After unziped thie file,I got six files including train.csv.
When I open train.csv,there are five items in the file.
Please look at the screenshot.
![image](https://user-images.githubusercontent.com/62454531/91656432-3d025a80-eaeb-11ea-880a-f9978f093920.png)
Did I downloaded the kinetics-400 in a wrong website or I downloaded a wrong knietics-400 file?

**Comment by chengxuz** [comment]
I believe they have modified the file format. The flag was not used anyway, I just removed that in newer committ. Thanks for pointing out this!

**Comment by Kaye-here** [comment]
Ok,I got it.Thank you very much for your help! ^0^
